
package GUI;

import Classes.UserAccounts;
import java.awt.Color;
import java.awt.Image;
import java.util.regex.*;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sham
 */
public class Sign_Page extends javax.swing.JFrame {

    /**
     * Creates new form Sign_Page
     */
    public Sign_Page() {
        initComponents();
        
    ImageIcon li =new ImageIcon(getClass().getResource("/Images/image.jpg"));
    Image image =(li).getImage().getScaledInstance(Right_Background.getWidth(), Right_Background.getHeight(),Image.SCALE_SMOOTH);
    li= new ImageIcon(image);
    Right_Background.setIcon(li);
    
    
        Right_Panel.setVisible(false);
        Left_Background.setVisible(false);
  
        txtPassword.setEchoChar('\u25cf');
        txtConfirm_Password.setEchoChar('\u25cf');
        txtNew_Password.setEchoChar('\u25cf');
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Left_Panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnSign_in = new javax.swing.JButton();
        btnCreat_User = new javax.swing.JButton();
        Left_Background = new javax.swing.JLabel();
        Right_Panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFirst_Name = new javax.swing.JTextField();
        txtLast_Name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNewEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNew_Password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtConfirm_Password = new javax.swing.JPasswordField();
        btnsignup = new javax.swing.JButton();
        Sign_Back = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Right_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Left_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Left_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setText("Sign In");
        Left_Panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 110, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Email");
        Left_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 150, -1));

        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        Left_Panel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 260, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Password");
        Left_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 70, -1));

        txtPassword.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        Left_Panel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 260, 40));

        jToggleButton1.setBackground(new java.awt.Color(238, 232, 232));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-hide-15.png"))); // NOI18N
        jToggleButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        Left_Panel.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 30, 40));

        btnSign_in.setBackground(new java.awt.Color(255, 102, 51));
        btnSign_in.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSign_in.setText("Sign In");
        btnSign_in.setBorder(null);
        btnSign_in.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSign_in.setFocusPainted(false);
        btnSign_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSign_inMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSign_inMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSign_inMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSign_inMouseReleased(evt);
            }
        });
        btnSign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSign_inActionPerformed(evt);
            }
        });
        Left_Panel.add(btnSign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 260, 40));

        btnCreat_User.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        btnCreat_User.setText("Create New User Account");
        btnCreat_User.setBorder(null);
        btnCreat_User.setBorderPainted(false);
        btnCreat_User.setContentAreaFilled(false);
        btnCreat_User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreat_User.setRequestFocusEnabled(false);
        btnCreat_User.setVerifyInputWhenFocusTarget(false);
        btnCreat_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreat_UserActionPerformed(evt);
            }
        });
        Left_Panel.add(btnCreat_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, 30));

        Main.add(Left_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 630));

        Left_Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Left_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image.jpg"))); // NOI18N
        Main.add(Left_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 630));

        Right_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Right_Panel.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("First Name");
        Right_Panel.add(jLabel4);
        jLabel4.setBounds(110, 200, 90, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Last Name");
        Right_Panel.add(jLabel5);
        jLabel5.setBounds(280, 200, 90, 20);

        txtFirst_Name.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        txtFirst_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        txtFirst_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirst_NameKeyReleased(evt);
            }
        });
        Right_Panel.add(txtFirst_Name);
        txtFirst_Name.setBounds(110, 220, 160, 40);

        txtLast_Name.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        txtLast_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        txtLast_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLast_NameKeyReleased(evt);
            }
        });
        Right_Panel.add(txtLast_Name);
        txtLast_Name.setBounds(280, 220, 160, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        Right_Panel.add(jLabel6);
        jLabel6.setBounds(110, 270, 314, 17);

        txtNewEmail.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        txtNewEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        txtNewEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewEmailKeyReleased(evt);
            }
        });
        Right_Panel.add(txtNewEmail);
        txtNewEmail.setBounds(110, 290, 330, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Password");
        Right_Panel.add(jLabel8);
        jLabel8.setBounds(110, 330, 314, 17);

        txtNew_Password.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        txtNew_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        txtNew_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNew_PasswordKeyReleased(evt);
            }
        });
        Right_Panel.add(txtNew_Password);
        txtNew_Password.setBounds(110, 350, 330, 42);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Confirm Password");
        Right_Panel.add(jLabel7);
        jLabel7.setBounds(110, 400, 314, 17);

        txtConfirm_Password.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        txtConfirm_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        txtConfirm_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirm_PasswordKeyReleased(evt);
            }
        });
        Right_Panel.add(txtConfirm_Password);
        txtConfirm_Password.setBounds(110, 420, 330, 42);

        btnsignup.setBackground(new java.awt.Color(255, 102, 51));
        btnsignup.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnsignup.setText("Sign up");
        btnsignup.setBorder(null);
        btnsignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsignup.setFocusPainted(false);
        btnsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsignupMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnsignupMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnsignupMouseReleased(evt);
            }
        });
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        Right_Panel.add(btnsignup);
        btnsignup.setBounds(110, 500, 330, 40);

        Sign_Back.setBackground(new java.awt.Color(153, 204, 255));
        Sign_Back.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        Sign_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/goback.png"))); // NOI18N
        Sign_Back.setText("BACK");
        Sign_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign_BackMouseClicked(evt);
            }
        });
        Right_Panel.add(Sign_Back);
        Sign_Back.setBounds(220, 580, 81, 26);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Sign Up");
        Right_Panel.add(jLabel3);
        jLabel3.setBounds(190, 120, 138, 48);

        Main.add(Right_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 1, 530, 630));

        Right_Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Right_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image.jpg"))); // NOI18N
        Main.add(Right_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 440, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewEmailKeyReleased
String PATTERN = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}";
Pattern patt = Pattern.compile(PATTERN);
Matcher match = patt.matcher(txtNewEmail.getText().trim());

if (!match.matches()) {
    txtNewEmail.setBorder(BorderFactory.createLineBorder(Color.RED));
} else {
    txtNewEmail.setBorder(BorderFactory.createLineBorder(Color.decode("#0ed145")));  
}
    }//GEN-LAST:event_txtNewEmailKeyReleased

    private void btnsignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsignupMouseEntered
        btnsignup.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnsignupMouseEntered

    private void btnsignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsignupMouseExited
        btnsignup.setBackground(new Color(255,102,51));
    }//GEN-LAST:event_btnsignupMouseExited

    private void btnsignupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsignupMousePressed
        btnsignup.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnsignupMousePressed

    private void btnsignupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsignupMouseReleased
        btnsignup.setBackground(new Color(255,102,51));
    }//GEN-LAST:event_btnsignupMouseReleased

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        boolean valid = true;

        UserAccounts user = new UserAccounts();
        boolean userExists = user.isUserExist(txtNewEmail.getText().trim());

        if (txtFirst_Name.getText().trim().isEmpty()
                || txtLast_Name.getText().trim().isEmpty()
                || txtNewEmail.getText().trim().isEmpty()
                || txtNew_Password.getText().trim().isEmpty()
                || txtConfirm_Password.getText().trim().isEmpty()) {
            JOptionPane:
            JOptionPane.showMessageDialog(null, "Feild can't be Empty", "Register Form", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else if (userExists) {
            JOptionPane.showMessageDialog(null, "User already exists!", "Error", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else {
            
            String PATTERN = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}";
            Pattern patt = Pattern.compile(PATTERN);
            Matcher match = patt.matcher(txtNewEmail.getText().trim());
            
            String firstNamePattern = "^[a-zA-Z]+$";
            String firstName = txtLast_Name.getText().trim();
            
            String lastNamePattern = "^[a-zA-Z]+$";
            String lastName = txtLast_Name.getText().trim();

            if (!firstName.matches(firstNamePattern)) {
                JOptionPane:
                JOptionPane.showMessageDialog(null, "Invalid First Name", "Register Form", JOptionPane.ERROR_MESSAGE);
                valid = false;
            }
            else if (!lastName.matches(lastNamePattern)) {
            JOptionPane:
                JOptionPane.showMessageDialog(null, "Invalid Last Name", "Register Form", JOptionPane.ERROR_MESSAGE);
                valid = false;
            }else if (!match.matches()) {
                JOptionPane:
                JOptionPane.showMessageDialog(null, "Invalid Email", "Register Form", JOptionPane.ERROR_MESSAGE);
                valid = false;

            }
            else if (txtNew_Password.getText().trim().length() < 8) {
                JOptionPane.showMessageDialog(null, "Password must have 8 characters", "Register form", JOptionPane.ERROR_MESSAGE);
                valid = false;
            } else if (!txtNew_Password.getText().trim().equals(txtConfirm_Password.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Password and Cinfirm Password should match", "Register form", JOptionPane.ERROR_MESSAGE);
                valid = false;
            }
        }

        if (valid) {

            String FName = txtFirst_Name.getText().trim().replace(" ", "_");
            String LName = txtLast_Name.getText().trim().replace(" ", "_");
            String Email = txtNewEmail.getText().trim();
            String Pass = txtNew_Password.getText().trim();

            UserAccounts newUser = new UserAccounts(FName, LName, Email, Pass);

            if (newUser.addUser()) {
                JOptionPane.showMessageDialog(null, "Account Add Successfully", "Register Form", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Sorry! Somthing Went Wrong", "Register Form", JOptionPane.WARNING_MESSAGE);
            }

            Sign_Page sp = new Sign_Page();
            sp.setVisible(true);

            this.dispose();

        }
    }//GEN-LAST:event_btnsignupActionPerformed

    private void Sign_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_BackMouseClicked
    ImageIcon li =new ImageIcon(getClass().getResource("/Images/image.jpg"));
    Image image2 =(li).getImage().getScaledInstance(Right_Background.getWidth(), Right_Background.getHeight(),Image.SCALE_SMOOTH);
    li= new ImageIcon(image2);
    Right_Background.setIcon(li);
    
      
        Right_Panel.setVisible(false);
        Right_Background.setVisible(true);
        Left_Background.setVisible(false);
        Left_Panel.setVisible(true);
    }//GEN-LAST:event_Sign_BackMouseClicked

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        if(jToggleButton1.isSelected())
        {txtPassword.setEchoChar((char)0);}
        else
        {txtPassword.setEchoChar('\u25cf');}
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void btnSign_inMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSign_inMouseEntered
        btnSign_in.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnSign_inMouseEntered

    private void btnSign_inMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSign_inMouseExited
        btnSign_in.setBackground(new Color(255,102,51));
    }//GEN-LAST:event_btnSign_inMouseExited

    private void btnSign_inMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSign_inMousePressed
        btnSign_in.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_btnSign_inMousePressed

    private void btnSign_inMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSign_inMouseReleased
        btnSign_in.setBackground(new Color(255,102,51));
    }//GEN-LAST:event_btnSign_inMouseReleased

    private void btnSign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSign_inActionPerformed
 boolean valid = true;
      UserAccounts user = new UserAccounts();
        String userid = txtEmail.getText().trim();
        String pass = txtPassword.getText().trim();
        
        
        if (txtEmail.getText().trim().isEmpty() || txtPassword.getText().trim().isEmpty()) {
            JOptionPane:
            JOptionPane.showMessageDialog(null, "Feild can't be Empty", "Signin", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }

        if (valid) {

            if (userid.equals("admin") && pass.equals("1234")) {
                JOptionPane:
                JOptionPane.showMessageDialog(null, "Sign in as Admin", "Sign in", JOptionPane.INFORMATION_MESSAGE);
                Administrator_Panel ap = new Administrator_Panel();
                ap.setVisible(true);
                this.dispose();
            } else if (user.login(userid, pass)) {
                // Login successful
               
                JOptionPane.showMessageDialog(null, "Login successful");
                                Index home = new Index();
                                home.setVisible(true);
                                this.dispose();
                                
            }else {
                // Login failed
               // System.out.println("Login failed");
                 JOptionPane.showMessageDialog(this, "Invalid Username or Password");
            }
        }
    }//GEN-LAST:event_btnSign_inActionPerformed

    private void btnCreat_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreat_UserActionPerformed
ImageIcon li =new ImageIcon(getClass().getResource("/Images/image.jpg"));
    Image image2 =(li).getImage().getScaledInstance(Left_Background.getWidth(), Left_Background.getHeight(),Image.SCALE_SMOOTH);
    li= new ImageIcon(image2);
    Left_Background.setIcon(li);
    
         Left_Panel.setVisible(false);
         Right_Panel.setVisible(true);
         Left_Background.setVisible(true);
         Right_Background.setVisible(false);
    }//GEN-LAST:event_btnCreat_UserActionPerformed

    private void txtFirst_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirst_NameKeyReleased
       String firstNamePattern = "^[a-zA-Z]+$";
String firstName = txtFirst_Name.getText().trim();

if (!firstName.matches(firstNamePattern)) {
    txtFirst_Name.setBorder(BorderFactory.createLineBorder(Color.RED));
} else {
    txtFirst_Name.setBorder(BorderFactory.createLineBorder(Color.decode("#0ed145")));
}

    }//GEN-LAST:event_txtFirst_NameKeyReleased

    private void txtLast_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLast_NameKeyReleased
              String firstNamePattern = "^[a-zA-Z]+$";
String lastName = txtLast_Name.getText().trim();

if (!lastName.matches(firstNamePattern)) {
    txtLast_Name.setBorder(BorderFactory.createLineBorder(Color.RED));
} else {
    txtLast_Name.setBorder(BorderFactory.createLineBorder(Color.decode("#0ed145")));
}
    }//GEN-LAST:event_txtLast_NameKeyReleased

    private void txtNew_PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNew_PasswordKeyReleased
     if(txtNew_Password.getText().trim().length()<8){
      txtNew_Password.setBorder(BorderFactory.createLineBorder(Color.RED));
     }else{
     txtNew_Password.setBorder(BorderFactory.createLineBorder(Color.decode("#0ed145")));
     }
    }//GEN-LAST:event_txtNew_PasswordKeyReleased

    private void txtConfirm_PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirm_PasswordKeyReleased
      if(!txtNew_Password.getText().trim().equals(txtConfirm_Password.getText())){
       txtConfirm_Password.setBorder(BorderFactory.createLineBorder(Color.RED));
      }else{
     txtConfirm_Password.setBorder(BorderFactory.createLineBorder(Color.decode("#0ed145")));
     }
     
    }//GEN-LAST:event_txtConfirm_PasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Left_Background;
    private javax.swing.JPanel Left_Panel;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel Right_Background;
    private javax.swing.JPanel Right_Panel;
    private javax.swing.JLabel Sign_Back;
    private javax.swing.JButton btnCreat_User;
    private javax.swing.JButton btnSign_in;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField txtConfirm_Password;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirst_Name;
    private javax.swing.JTextField txtLast_Name;
    private javax.swing.JTextField txtNewEmail;
    private javax.swing.JPasswordField txtNew_Password;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
